import puppeteer from 'puppeteer-core';
const exe = '.browser/chrome-headless-shell/mac_arm64-152.0.7977.64/chrome-headless-shell';
const browser = await puppeteer.launch({ executablePath: exe, args: ['--no-sandbox'] });
const page = await browser.newPage();
let fail = 0;
const ok = (l, c, x) => { if (!c) { fail++; console.log('FAIL ' + l + (x ? ' :: ' + x : '')) } else console.log('ok   ' + l) };
await page.setViewport({ width: 412, height: 915, deviceScaleFactor: 2.625, isMobile: true, hasTouch: true });
await page.goto('http://127.0.0.1:4317/', { waitUntil: 'domcontentloaded', timeout: 15000 });
await new Promise(r => setTimeout(r, 1200));
await page.evaluate(() => document.querySelectorAll('.appTabs .appTab')[7].click());
await new Promise(r => setTimeout(r, 700));
ok('滑杆数量 8', (await page.evaluate(() => document.querySelectorAll('.slider input[type=range]').length)) === 8);
const drag = (idx, val) => page.evaluate((i, v) => {
  const el = document.querySelectorAll('.slider input[type=range]')[i];
  const setter = Object.getOwnPropertyDescriptor(window.HTMLInputElement.prototype, 'value').set;
  setter.call(el, String(v));
  el.dispatchEvent(new Event('input', { bubbles: true }));
}, idx, val);
await drag(0, 30);
await new Promise(r => setTimeout(r, 250));
let v = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--gv-veil').trim());
ok('veil → --gv-veil=0.300', v === '0.300', v);
await drag(4, 55);
await new Promise(r => setTimeout(r, 250));
const d = await page.evaluate(() => { const e = document.getElementById('hst-disp'); return e ? e.getAttribute('scale') : 'no-filter' });
ok('disp → SVG scale=55', d === '55' || d === '55.0', d);
const h0 = await page.evaluate(() => { const e = document.getElementById('hst-norm'); return e ? e.getAttribute('href').slice(22, 122) : '' });
await drag(5, 28);
await new Promise(r => setTimeout(r, 400));
const h1 = await page.evaluate(() => { const e = document.getElementById('hst-norm'); return e ? e.getAttribute('href').slice(22, 122) : '' });
ok('band → 法线贴图重生成', h0 !== '' && h1 !== '' && h0 !== h1, 'changed=' + (h0 !== h1));
await page.reload({ waitUntil: 'domcontentloaded' });
await new Promise(r => setTimeout(r, 1000));
v = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--gv-veil').trim());
ok('刷新后持久化 0.300', v === '0.300', v);
await page.evaluate(() => document.querySelectorAll('.appTabs .appTab')[7].click());
await new Promise(r => setTimeout(r, 500));
await page.evaluate(() => [...document.querySelectorAll('.card h3')].find(h => h.textContent === '液态玻璃').parentElement.querySelector('.btn').click());
await new Promise(r => setTimeout(r, 250));
v = await page.evaluate(() => getComputedStyle(document.documentElement).getPropertyValue('--gv-veil').trim());
ok('恢复默认 → 0.100', v === '0.100', v);
await page.screenshot({ path: '.preview/glass-settings.png' });
await browser.close();
console.log(fail === 0 ? 'SLIDERS-OK' : 'SLIDERS-FAIL x' + fail);
process.exit(fail ? 1 : 0);